### ISSUE TITLE
Dependency guard requires > 1GB of memory for library

### ISSUE THREAD

**Issue by willemstuursma** [mediact/dependency-guard#25]
# Description

Running dependency guard on my project fails because it crashes with an out of memory warning. 

```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 36864 bytes) in /home/travis/build/php-twinfield/twinfield/vendor/nikic/php-parser/lib/PhpParser/ParserFactory.php on line 28
```
You can see the build output here: https://travis-ci.org/php-twinfield/twinfield/jobs/436207071

# Steps to Reproduce

1. Clone https://github.com/php-twinfield/twinfield
2. Run dependency guard
3. Crash!

**Expected behavior:** [What you expect to happen]

Don't take > 1GB for analyzing a < 50K loc project

**Actual behavior:** [What actually happens]

Out of memory crash

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% 

# Versions

You can get this information from copy and pasting the output of:

* As dependency: `composer show mediact/dependency-guard | grep version`
* As root package: `composer show --self | grep version`

latest versions (no lock files used)

**Comment by johmanx10** [comment]
@willemstuursma I cannot reproduce this error at 1024M memory limit in a regression test, but I can get the same result at 512M and will continue with that as limit.
