### ISSUE TITLE
ext-json ^1.5 cannot be install with php 7.4.2

### ISSUE THREAD

**Issue by Axent96** [mediact/dependency-guard#37]
# Description
composer install with PHP 7.4

[Description of the issue]

# Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]
mediact/dependency-guard 1.1.0 requires ext-json ^1.5 -> the requested PHP extension json has the wrong version (7.4.2) installed
**Reproduces how often:** [What percentage of the time does it reproduce?]
composer install or composer update
# Versions
1.1.0
You can get this information from copy and pasting the output of:

* As dependency: `composer show mediact/dependency-guard | grep version`
* As root package: `composer show --self | grep version`

**Comment by Axent96** [comment]
Now, in PHP 7.4+, it is following the same as other extensions: PHP's version number
https://github.com/lcobucci/content-negotiation-middleware/issues/31

**Comment by ksangers** [comment]
@Axent96 Just released this under https://github.com/mediact/dependency-guard/releases/tag/1.1.1. Enjoy :)
