### ISSUE TITLE
Problem with Composer v2

### ISSUE THREAD

**Issue by Axent96** [mediact/dependency-guard#41]
# Description
composer install

[Description of the issue]

# Steps to Reproduce

1. composer install

# Versions
composer v 2.0.3

You can get this information from copy and pasting the output of:
composer install 

mediact/dependency-guard is locked to version 1.1.1 and an update of this package was not requested.
    - mediact/dependency-guard 1.1.1 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint

**Comment by Axent96** [comment]
@ksangers do you can please approve the pull request? - #43

**Comment by ksangers** [comment]
Yes, done so now. 1.1.2
