### ISSUE TITLE
Don't fail if a dev exception class is part of a catch clause

### ISSUE THREAD

**Issue by willemstuursma** [mediact/dependency-guard#7]
We have some code set up like this:

```php
try {
   // ... some code
} catch (\PHPUnit\Framework\AssertionFailedError $e) {
   throw $e;
} catch (\Thowable $e) {
  // some error handling
}
```

This is so that assertions during tests bubble up to PHPUnit and don't cause the generic exception handling to be invoked.

This doesn't cause any issues in production actually. PHP does not try to load the class, because if it is not already loaded, it can never have been thrown. 

Could you skip dev dependency class references in catch statements?

**Comment by willemstuursma** [comment]
I must say that I am impressed, it works well and fast. We don't have a small code base and have lots of dependencies. 

Will probably contribute some minor performance improvements in the future.

**Comment by johmanx10** [comment]
@willemstuursma are you willing to have a small video call about this, where you can properly show me the context in which this makes sense for you? I want to be pretty thorough and strict about behavioral updates for this tool, which you will probably appreciate.

**Comment by johmanx10** [comment]
Additionally, I'm curious if existing functionality is able to help you out bridge the gap while this has not been resolved: https://github.com/mediact/dependency-guard#exclude-symbols
It is possible to exclude symbols from analysis, which will probably solve your problem for now.

**Comment by willemstuursma** [comment]
@johmanx10 yes we can work around it. Of course we can have a call, can you send me your skype username and your availability for next week: willem@mollie.com.
